### ISSUE TITLE
 Code running error

### ISSUE THREAD

**Issue by wenchao-zhao** [arjunsundaram4/Job-Shop-SCHEDULING#2]

**Comment by arjunsundaram4** [comment]
This is probably because the input format isn't right

**Comment by wenchao-zhao** [comment]
> This is probably because the input format isn't right

Sorry, I run directly in the folder called Behnke35.fjs.
![image](https://user-images.githubusercontent.com/71486725/110928952-65082b80-8362-11eb-90f9-92413ba21e43.png)

**Comment by wenchao-zhao** [comment]
> Hello, there was an error while running genetikalgoritma. What caused it?The error message is：list index out of range
